# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logic.protogen.teacher_pb2 as teacher__pb2


class TeacherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCodeAndStart = channel.unary_unary(
                '/teacher.Teacher/GenerateCodeAndStart',
                request_serializer=teacher__pb2.GenerateCodeAndStartRequest.SerializeToString,
                response_deserializer=teacher__pb2.GenerateCodeAndStartResponse.FromString,
                )
        self.EditCountdown = channel.unary_unary(
                '/teacher.Teacher/EditCountdown',
                request_serializer=teacher__pb2.EditCountdownRequest.SerializeToString,
                response_deserializer=teacher__pb2.EditCountdownResponse.FromString,
                )
        self.DeleteCode = channel.unary_unary(
                '/teacher.Teacher/DeleteCode',
                request_serializer=teacher__pb2.DeleteCodeRequest.SerializeToString,
                response_deserializer=teacher__pb2.DeleteCodeResponse.FromString,
                )


class TeacherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCodeAndStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditCountdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeacherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCodeAndStart': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCodeAndStart,
                    request_deserializer=teacher__pb2.GenerateCodeAndStartRequest.FromString,
                    response_serializer=teacher__pb2.GenerateCodeAndStartResponse.SerializeToString,
            ),
            'EditCountdown': grpc.unary_unary_rpc_method_handler(
                    servicer.EditCountdown,
                    request_deserializer=teacher__pb2.EditCountdownRequest.FromString,
                    response_serializer=teacher__pb2.EditCountdownResponse.SerializeToString,
            ),
            'DeleteCode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCode,
                    request_deserializer=teacher__pb2.DeleteCodeRequest.FromString,
                    response_serializer=teacher__pb2.DeleteCodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'teacher.Teacher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Teacher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCodeAndStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teacher.Teacher/GenerateCodeAndStart',
            teacher__pb2.GenerateCodeAndStartRequest.SerializeToString,
            teacher__pb2.GenerateCodeAndStartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditCountdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teacher.Teacher/EditCountdown',
            teacher__pb2.EditCountdownRequest.SerializeToString,
            teacher__pb2.EditCountdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teacher.Teacher/DeleteCode',
            teacher__pb2.DeleteCodeRequest.SerializeToString,
            teacher__pb2.DeleteCodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
