# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teacher.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teacher.proto',
  package='teacher',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rteacher.proto\x12\x07teacher\"!\n\x13GenerateCodeRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"\'\n\x15StartCountdownRequest\x12\x0e\n\x06millis\x18\x01 \x01(\x05\"(\n\x16\x45xtendCountdownRequest\x12\x0e\n\x06millis\x18\x01 \x01(\x05\"$\n\x14GenerateCodeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"%\n\x16StartCountdownResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"&\n\x17\x45xtendCountdownResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x85\x02\n\x07Teacher\x12M\n\x0cGenerateCode\x12\x1c.teacher.GenerateCodeRequest\x1a\x1d.teacher.GenerateCodeResponse\"\x00\x12S\n\x0eStartCountdown\x12\x1e.teacher.StartCountdownRequest\x1a\x1f.teacher.StartCountdownResponse\"\x00\x12V\n\x0f\x45xtendCountdown\x12\x1f.teacher.ExtendCountdownRequest\x1a .teacher.ExtendCountdownResponse\"\x00\x62\x06proto3'
)




_GENERATECODEREQUEST = _descriptor.Descriptor(
  name='GenerateCodeRequest',
  full_name='teacher.GenerateCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='teacher.GenerateCodeRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_STARTCOUNTDOWNREQUEST = _descriptor.Descriptor(
  name='StartCountdownRequest',
  full_name='teacher.StartCountdownRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='millis', full_name='teacher.StartCountdownRequest.millis', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=100,
)


_EXTENDCOUNTDOWNREQUEST = _descriptor.Descriptor(
  name='ExtendCountdownRequest',
  full_name='teacher.ExtendCountdownRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='millis', full_name='teacher.ExtendCountdownRequest.millis', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=142,
)


_GENERATECODERESPONSE = _descriptor.Descriptor(
  name='GenerateCodeResponse',
  full_name='teacher.GenerateCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='teacher.GenerateCodeResponse.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=180,
)


_STARTCOUNTDOWNRESPONSE = _descriptor.Descriptor(
  name='StartCountdownResponse',
  full_name='teacher.StartCountdownResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='teacher.StartCountdownResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=219,
)


_EXTENDCOUNTDOWNRESPONSE = _descriptor.Descriptor(
  name='ExtendCountdownResponse',
  full_name='teacher.ExtendCountdownResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='teacher.ExtendCountdownResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=259,
)

DESCRIPTOR.message_types_by_name['GenerateCodeRequest'] = _GENERATECODEREQUEST
DESCRIPTOR.message_types_by_name['StartCountdownRequest'] = _STARTCOUNTDOWNREQUEST
DESCRIPTOR.message_types_by_name['ExtendCountdownRequest'] = _EXTENDCOUNTDOWNREQUEST
DESCRIPTOR.message_types_by_name['GenerateCodeResponse'] = _GENERATECODERESPONSE
DESCRIPTOR.message_types_by_name['StartCountdownResponse'] = _STARTCOUNTDOWNRESPONSE
DESCRIPTOR.message_types_by_name['ExtendCountdownResponse'] = _EXTENDCOUNTDOWNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateCodeRequest = _reflection.GeneratedProtocolMessageType('GenerateCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATECODEREQUEST,
  '__module__' : 'teacher_pb2'
  # @@protoc_insertion_point(class_scope:teacher.GenerateCodeRequest)
  })
_sym_db.RegisterMessage(GenerateCodeRequest)

StartCountdownRequest = _reflection.GeneratedProtocolMessageType('StartCountdownRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTCOUNTDOWNREQUEST,
  '__module__' : 'teacher_pb2'
  # @@protoc_insertion_point(class_scope:teacher.StartCountdownRequest)
  })
_sym_db.RegisterMessage(StartCountdownRequest)

ExtendCountdownRequest = _reflection.GeneratedProtocolMessageType('ExtendCountdownRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDCOUNTDOWNREQUEST,
  '__module__' : 'teacher_pb2'
  # @@protoc_insertion_point(class_scope:teacher.ExtendCountdownRequest)
  })
_sym_db.RegisterMessage(ExtendCountdownRequest)

GenerateCodeResponse = _reflection.GeneratedProtocolMessageType('GenerateCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERATECODERESPONSE,
  '__module__' : 'teacher_pb2'
  # @@protoc_insertion_point(class_scope:teacher.GenerateCodeResponse)
  })
_sym_db.RegisterMessage(GenerateCodeResponse)

StartCountdownResponse = _reflection.GeneratedProtocolMessageType('StartCountdownResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTCOUNTDOWNRESPONSE,
  '__module__' : 'teacher_pb2'
  # @@protoc_insertion_point(class_scope:teacher.StartCountdownResponse)
  })
_sym_db.RegisterMessage(StartCountdownResponse)

ExtendCountdownResponse = _reflection.GeneratedProtocolMessageType('ExtendCountdownResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDCOUNTDOWNRESPONSE,
  '__module__' : 'teacher_pb2'
  # @@protoc_insertion_point(class_scope:teacher.ExtendCountdownResponse)
  })
_sym_db.RegisterMessage(ExtendCountdownResponse)



_TEACHER = _descriptor.ServiceDescriptor(
  name='Teacher',
  full_name='teacher.Teacher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=262,
  serialized_end=523,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateCode',
    full_name='teacher.Teacher.GenerateCode',
    index=0,
    containing_service=None,
    input_type=_GENERATECODEREQUEST,
    output_type=_GENERATECODERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartCountdown',
    full_name='teacher.Teacher.StartCountdown',
    index=1,
    containing_service=None,
    input_type=_STARTCOUNTDOWNREQUEST,
    output_type=_STARTCOUNTDOWNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExtendCountdown',
    full_name='teacher.Teacher.ExtendCountdown',
    index=2,
    containing_service=None,
    input_type=_EXTENDCOUNTDOWNREQUEST,
    output_type=_EXTENDCOUNTDOWNRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEACHER)

DESCRIPTOR.services_by_name['Teacher'] = _TEACHER

# @@protoc_insertion_point(module_scope)
