# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import logic.protogen.teacher_pb2 as teacher__pb2


class TeacherStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCode = channel.unary_unary(
                '/teacher.Teacher/GenerateCode',
                request_serializer=teacher__pb2.GenerateCodeRequest.SerializeToString,
                response_deserializer=teacher__pb2.GenerateCodeResponse.FromString,
                )
        self.StartCountdown = channel.unary_unary(
                '/teacher.Teacher/StartCountdown',
                request_serializer=teacher__pb2.StartCountdownRequest.SerializeToString,
                response_deserializer=teacher__pb2.StartCountdownResponse.FromString,
                )
        self.ExtendCountdown = channel.unary_unary(
                '/teacher.Teacher/ExtendCountdown',
                request_serializer=teacher__pb2.ExtendCountdownRequest.SerializeToString,
                response_deserializer=teacher__pb2.ExtendCountdownResponse.FromString,
                )


class TeacherServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCountdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtendCountdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeacherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCode,
                    request_deserializer=teacher__pb2.GenerateCodeRequest.FromString,
                    response_serializer=teacher__pb2.GenerateCodeResponse.SerializeToString,
            ),
            'StartCountdown': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCountdown,
                    request_deserializer=teacher__pb2.StartCountdownRequest.FromString,
                    response_serializer=teacher__pb2.StartCountdownResponse.SerializeToString,
            ),
            'ExtendCountdown': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtendCountdown,
                    request_deserializer=teacher__pb2.ExtendCountdownRequest.FromString,
                    response_serializer=teacher__pb2.ExtendCountdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'teacher.Teacher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Teacher(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teacher.Teacher/GenerateCode',
            teacher__pb2.GenerateCodeRequest.SerializeToString,
            teacher__pb2.GenerateCodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartCountdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teacher.Teacher/StartCountdown',
            teacher__pb2.StartCountdownRequest.SerializeToString,
            teacher__pb2.StartCountdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExtendCountdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teacher.Teacher/ExtendCountdown',
            teacher__pb2.ExtendCountdownRequest.SerializeToString,
            teacher__pb2.ExtendCountdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
