
from interface.screens.login import LoginScreen
from interface.screens.create_user import CreateUserScreen
from interface.screens.about import AboutScreen

from interface.screens.student_screens.student_dashboard import StudentDashboardScreen
from interface.screens.student_screens.submit_check_in import SubmitCheckInScreen
from interface.screens.student_screens.student_stats import StudentStatsScreen

from interface.screens.teacher_screens.teacher_dashboard import TeacherDashboardScreen
from interface.screens.teacher_screens.teacher_stats import TeacherStatsScreen
from interface.screens.teacher_screens.group_overview import GroupOverviewScreen
from interface.screens.teacher_screens.create_group import CreateGroupScreen

