[development]
[development.database]
host="localhost"
port=30302

[development.server]
host="localhost"
port=30303

[production]
[production.database]
host="localhost"
port=30302

[production.server]
host="localhost"
port=30303


[testing]
[testing.database]
host="localhost"
port=30302

[testing.server]
host="localhost"
port=30303
